services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pixel_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      # creates an additional pixel_db_test database for running tests against
      - ./backend/scripts/init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql

volumes:
  db-data: